trigger: none

schedules:
- cron: "0 9 * * *"
  displayName: Daily 9 AM Build
  branches:
    include:
      - dev
  always: true

pool:
  name: Batch13-agents

stages:
- stage: copyfiles
  displayName: Copying files to Blob

  jobs:
  - job: AzureBlobCopyJob
    steps:
    - task: AzureFileCopy@6
      displayName: StorageAccountFileTransfer
      inputs:
        SourcePath: 'class2.txt'
        azureSubscription: 'VDSP'
        Destination: 'AzureBlob'
        storage: 'vdsa133'
        ContainerName: 'vdc'