trigger: none

pool:
  name: DevopsPool

steps:

- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    connectionType: azureResourceManager
    azureSubscriptionConnection: myservice
    azureResourceGroup: Rohith
    kubernetesCluster: rpcluster
    manifests: deployment.yaml
