FROM ubuntu:24.04
RUN apt-get update
RUN apt-get install -y openjdk-21-jdk 
RUN apt-get install -y wget
WORKDIR /home/project
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.117/bin/apache-tomcat-9.0.117.tar.gz
RUN tar -xzf apache-tomcat-9.0.117.tar.gz
COPY Amazon.war apache-tomcat-9.0.117/webapps/Amazon.war
EXPOSE 8080
CMD ["./apache-tomcat-9.0.117/bin/catalina.sh", "run"] 
