# Stage 1 - Builder
FROM python:3.12 AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --prefix=/install -r requirements.txt

COPY . .

# Stage 2 - Runtime
FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY --from=builder /app /app

CMD ["python", "app.py"]
