version: "3.8"

services:
  amazon:
    image: amazon:war01
    container_name: amazon-v1
    ports:
      - "8081:8080"
    networks:
      - app-network
    volumes:
      - amazon-data:/usr/local/tomcat/webapps

  appjar:
    image: springboot:jar01
    container_name: springboot-v1
    ports:
      - "8085:8085"
    networks:
      - app-network
    volumes:
      - springboot-data:/app/data

networks:
  app-network:
    driver: bridge

volumes:
  amazon-data:
    driver: local

  springboot-data:
    driver: local
