---
 - name: copy module
   hosts: all
   gather_facts: no

   tasks:

      - name: copy_module
        copy:
          content: "helo from control node"
          dest: "/tmp/text.txt"


      - name: copy file from local to remote
        copy: 
          src: sample.txt #this file is create in local machine 
          dest: "/tmp/sample.txt"
          owner: azureuser #owner of file
          mode: "777" #file permission

