---
- name: delete 50 files
  hosts: webservers
  gather_facts: no

  tasks:

    - name: remove files from demo1
      file:
        path: "/tmp/demo1/file{{ item }}.txt"
        state: absent
      loop: "{{ range(1,51) | list }}"
