---
- name: create 50 files and move in batches of 5
  hosts: webservers
  gather_facts: no

  vars:
    file_batches: "{{ range(1,51) | list | batch(5) }}"

  tasks:

    - name: create local dir
      file:
        path: /tmp/demo1
        state: directory

    - name: create dest dir
      file:
        path: /tmp/demo2
        state: directory

    - name: create files
      file:
        path: "/tmp/demo1/file{{ item }}.txt"
        state: touch
      loop: "{{ range(1,51) | list }}"

    - name: move files batch wise (5 at a time logically)
      command: mv /tmp/demo1/file{{ item }}.txt /tmp/demo2/
      loop: "{{ file_batches | flatten }}" #flatten avooids grouping of 
