---
- name: Demonstrate Always Tag
  hosts: client_servers
  become: true
  tasks:
    - name: Gather deployment information
      debug:
        msg: This task always runs
      tags:
        - always
    - name: installing java
      apt:
        name: openjdk-11-jdk
        state: present
      tags:
        - java
    - name: creating tomcat directory
      file:
        path: /opt/tomcat
        state: directory
      tags:
        - tomcat
