apiVersion: v1

kind: Pod

metadata:

  name: api-pod

  labels:

    app: api

spec:

  containers:

  - name: api

    image: adikarthik/demo

    ports:

    - containerPort: 9090

    readinessProbe:

      httpGet:

        path: /healthz

        port: 9090
