apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "debug"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app
    image: tomcat:latest
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: app-config
