apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
X      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: gousia00/myfirstimage:2.7
        name: myfirstimage
        resources: {}
status: {}
