apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
    name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        app: demo1
        name: test
    spec:
      containers:
        - name: demo
          image: deepa/demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
