apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo
  labels:
    app: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo

  serviceName: demo

  template:
    metadata:
      labels:
        app: demo

    spec:
      containers:
      - name: demo
        image: nginx

        ports:
        - containerPort: 9090
